version: "3.9"
services:
  database:
    image: postgres:latest
    restart: always
    container_name: audio-library-db
    environment:
      - POSTGRES_DB=laborator
      - POSTGRES_USER=audiolib
      - POSTGRES_PASSWORD=123456
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: victor.cucu@ici.ro
      PGADMIN_DEFAULT_PASSWORD: 907K12
    ports:
      - "8080:80"
    depends_on:
      - database
